### PR TITLE
Fixes#216 Added a team member

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Added Parth Shandilya's image along with credentials. GCI mentor
Deploy link: https://arjunpandey2003.github.io/arjunfossasia.org/
Check out the team page

### CODE REVIEW

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Please change your PR title to `Fixes #<issue-number>: <message>` and kindly squash your commits and change your commit message to something relevant

**Review by vaibhavsingh97 — APPROVED** [review]
LGTM

**Review by NaviRocker — APPROVED** [review]
LGTM

**Comment by samyakbvs** [comment]
@arjunpandey2003 have you added him in the fossasia developers section

**Comment by arjunpandey2003** [comment]
@samyakbvs yes in the team page under developers

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
