### PR TITLE
Copyright text made visible

### PR DESCRIPTION
**Pull request by onkar-shaligram**
Copyright text is now made visible
Solved issue #749

**Before:--**
Screenshot (46)_LI

**After:--**
Screenshot (45)_LI

### CODE REVIEW

**Comment by onkar-shaligram** [comment]
@Dishebh @liveHarshit please Review. You can preview the changes at https://amazing-einstein-55a359.netlify.app/

**Review by Dishebh — APPROVED** [review]
Try squashing your commits from next time. I see you're bringing commits from other branches as well.

**Comment by onkar-shaligram** [comment]
Alright, @Dishebh I will squash the commits from next time.

**Review by liveHarshit — CHANGES_REQUESTED** [review]
stale

**Review by liveHarshit — APPROVED** [review]

**Pull request merged**
