### PR TITLE
Instagram link added

### LINKED ISSUE #30: Adding Instagram link at the bottom of the page
Since we have a Instagram page too, so why can't we provide a link to that as like our fb, twitter accounts.

### PR DESCRIPTION
**Pull request by SilentFlame**
resolves #30 
@jig08 please review and merge.

### CODE REVIEW

**Comment by SilentFlame** [comment]
since our website has the `youtube` and `flicker` links at two places so I think these should be consistent.

**Comment by jigyasa-grover** [comment]
@SilentFlame This PR has merge conflicts ...

**Comment by SilentFlame** [comment]
I'm unable to understand that, can you please help. @jig08

**Comment by jigyasa-grover** [comment]
@SilentFlame `Merge Conflict` happens when two branches have changed the same part of the same file, and then those branches are merged together. Refer [GitHub Help](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/) for details and help.

**Comment by SilentFlame** [comment]
I guess this works now. @jig08 
have a look.

**Comment by jigyasa-grover** [comment]
Nope @SilentFlame

**Comment by SilentFlame** [comment]
I think removing the previous and doing all again makes sense, and do works. @jig08.

**Comment by SilentFlame** [comment]
Now this the entire change is done in one commit. Hope this works. :)

**Comment by jigyasa-grover** [comment]
@SilentFlame Doing stuff in one commit doesn't guarantee a conflict free PR.
This Pull Request still has merge conflicts. You could refer the steps [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) in the guide we made for GCI students and contributors during Google Code-In :) Hope that helps.

**Comment by SilentFlame** [comment]
Let me go through it, and for the help and guide I really thank you. @jig08

**Comment by SilentFlame** [comment]
I guess this should now be closed. @jig08  
as the same has been merged from @ashutoshsaboo .

I'll keep in mind the cases to not have merge conflicts from next times.. Thanks for the guidance. :smiley:

**Comment by jigyasa-grover** [comment]
Oh, Yeah sure :v:

**Pull request closed without merging**
