### PR TITLE
feat: Add back to top button

### LINKED ISSUE #474: Include a back-to-top button on scrolling down
On scrolling the website, a back-to-top button can be included in the bottom-right corner to make it easier to navigate back to the top. Only show the back to top button when the use moves the page. Ensure you use the existing scrolling implementation.

This issue is available for anyone. You can just start working on it without getting assigned.

### PR DESCRIPTION
**Pull request by ji-kun**
Fixes #474

Here's a link to the preview:

https://fossasia.kunji.me/

### CODE REVIEW

**Review by liveHarshit — COMMENTED** [review]
Please provide a preview URL.

**Comment by ji-kun** [comment]
Sorry for the late reply,
Here's a link to the preview:

https://fossasia.kunji.me/

**Review by liveHarshit — APPROVED** [review]

**Comment by mariobehling** [comment]
This change broke the scrolling from the top menu bar. The user had to click three times to get to the links on the page. Therefore I have to revert it. 

It would be better if the already available scrolling implementation would be used and if any scripts would be stored outside of the html. Would be great if you could re-implement this.

**Comment by mariobehling** [comment]
Automatic revert is not possible. I will revert this manually.

**Pull request merged**
