### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by luckykumardev**
I have added a javascript library(scrollreveal) to project. which will animate our landing page when we scroll.

### CODE REVIEW

**Comment by mariobehling** [comment]
Why? Where is the issue? Test page?

**Review by isuruAb — CHANGES_REQUESTED** [review]
please mention the issue number in the Pull request body. please refer other pull requests . and please read this for best practices.
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by luckykumardev** [comment]
sorry, actually I am new at GitHub(open source). it was not any issue. I just updated index.html to enhance the user experience for this website.
@mariobehling 
@isuruAb

**Review by isuruAb — COMMENTED** [review]
@luckykumardev , if you have done some thing or fixed any issue, please add a preview link. it helps reviewers to review your codes.

**Review by luckykumardev — COMMENTED** [review]
fossasia

**Comment by luckykumardev** [comment]
https://github.com/fossasia/fossasia.org/pull/192/commits/a842a4093826c959afc42d9135ded1bdb72bb248
@isuruAb

**Review by isuruAb — COMMENTED** [review]
please open an issue first here:
https://github.com/fossasia/fossasia.org/issues
then mention that issue number in pull request body and it's title. cheers 👍

**Comment by mariobehling** [comment]
Nice effect, but not needed to make the site work better.

**Pull request closed without merging**
