### PR TITLE
Added Zameer, GCI mentor

### LINKED ISSUE #216: Add members and improve team page: Developers, GCI/GSoC mentors, students etc.
The team page at https://fossasia.org/team is missing team members and missing information including:
* mentors of GCI/GSoC
* GSoC students of 2016 and 2017 into section "Alumni"
* Codeheat finalists into section "Alumni"
* FOSSASIA Summit organizers

**Note**: Only keep people in one category, e.g. if they already show up on the advisory board there is no need to add them again to the event organizer section.

### PR DESCRIPTION
**Pull request by 0x48piraj**
### Added Zameer Ul Haque to `team.html`
image

**Preview Link** - **_http://0x48piraj.github.io/fossasia.org/team.html_**

### CODE REVIEW

**Review by haquezameer — APPROVED** [review]
lgtm

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@0x48piraj why you have changed hong phuc dang image ? Please keep it as it was before .

**Comment by 0x48piraj** [comment]
@ParthS007 It's a previous commit, Check the website.

> Just reflected when I used `git reset`

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
@0x48piraj Please don't make changes that are not related to PR.

**Comment by 0x48piraj** [comment]
@ParthS007 @vaibhavsingh97 

It just reflected. It's there for 3 years.
I'm going to check. **Thanks !**
> https://github.com/fossasia/fossasia.org/blob/gh-pages/img/HongPhucDang.jpg **(600x600)**

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@ParthS007 After final review, please merge this PR

**Review by dilpreetsio — APPROVED** [review]

**Comment by 0x48piraj** [comment]
Thanks @mariobehling :sparkles:

**Pull request merged**
