### PR TITLE
Navbar-License issue resolved

### LINKED ISSUE #669: In side Navbar "Copyright 2009-2019 Creative Commons By License, FOSSASIA FOSSASIA" isn't visible
Inside the side navbar, the bottom line isn't visible fully.
Will like to work on it.
Screenshot (92)

### PR DESCRIPTION
**Pull request by Yashank18**
Fixes #669 The issue with the side navbar resolved.

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
Also change ~2019~ 2020

**Comment by Yashank18** [comment]
@snitin315 
Done.

**Comment by snitin315** [comment]
Add  `Fixes #669` in PR Description.

**Comment by Yashank18** [comment]
@snitin315 
Added Fixes #669 in Description

**Comment by snitin315** [comment]
Description not title.

**Comment by Yashank18** [comment]
@snitin315 
Done

**Review by snitin315 — APPROVED** [review]

**Comment by abishekvashok** [comment]
A working demo is highly appreciated. Please provide one

**Comment by Yashank18** [comment]
@abishekvashok 
Here is the Demo Picture of Before and after.
Before
Screenshot (92)

After
Screenshot (93)

**Comment by Yashank18** [comment]
@abishekvashok Sir can you please merge my PR as it's 12 days now

**Pull request merged**
