### PR TITLE
Add a developer

### PR DESCRIPTION
**Pull request by akshit15013**
Description : Add a developer Mayank Vaidya to the Team section
Link to the website : https://akshit15013.github.io/fossasia9.org/team/
Issue No. : #360 
screenshot 136

### CODE REVIEW

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, COULD YOU PLEASE MERGE IT?

**Comment by akshit15013** [comment]
@mariobehling @fragm3

**Comment by supunTE** [comment]
LGTM!

**Review by sarnava1 — APPROVED** [review]
LGTM

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by akshit15013** [comment]
@mariobehling There are no conflicts in it

**Pull request closed without merging**
