### PR TITLE
Add Diego Mora Cespedes as team member Fixes #263

### LINKED ISSUE #263: Add Diego Mora Cespedes as team member
Diego Mora Cespedes is missing as team member. I'm going to add him 😄

### PR DESCRIPTION
**Pull request by kubami9**
**Add Diego Mora Cespedes as team member Fixes #263**

Preview link: https://kubami9.github.io/fossasia.org-km-contribute/team

### CODE REVIEW

**Review by rupav — APPROVED** [review]
Good work. From where did you find that added member is associated to fossasia?

**Comment by mariobehling** [comment]
Not a core member.

**Comment by kubami9** [comment]
@mariobehling @rupav I added team member based on my mentor advice which was "Add anyone from this list to the Developers section
https://github.com/orgs/fossasia/teams/fossasia-gci/members" 
If it's not the proper place to find team member, could you tell me please where can I find him?

**Comment by mariobehling** [comment]
Some people are only associated and support FOSSASIA as members of other communities. So, they are mentors, but not FOSSASIA team members. Please check on that when you add team members. Cheers.

**Comment by kubami9** [comment]
@mariobehling So I know if someone is FOSSASIA team member if he/she has FOSSASIA organisation membership?

**Pull request closed without merging**
