### PR TITLE
Removed the horizontal scrolling issue

### PR DESCRIPTION
**Pull request by Dishebh**
Fix for issue #606 

Test link: https://dishebh.github.io/fossasia.org/

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Instead of hiding the overflow the question is where does this horizontal bar now come from? Please help to identify it and let's get rid of the cause.

**Comment by Dishebh** [comment]
@mariobehling found the cause, it is due to the class col-sm-12 in the projects and android section of the webpage.

**Comment by Dishebh** [comment]
@mariobehling I solved the root cause of the issue.
Test link: https://dishebh.github.io/fossasia.org/

**Review by mariobehling — CHANGES_REQUESTED** [review]
This is not following standard practices. Use CSS instead of br tag.

**Comment by Dishebh** [comment]
Done @mariobehling 
Test Link: https://dishebh.github.io/fossasia.org/

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
