### PR TITLE
Added Abhishek V Ashok to the Fossasia team page

### LINKED ISSUE #352: Abhishek V Ashok not present on Team Page
Need to add @abishekvashok to team page.

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #352 
https://saarthakchats.github.io/wassap/team/

### CODE REVIEW

**Comment by saarthakchats** [comment]
@abishekvashok

**Review by sarnava1 — COMMENTED** [review]
LGTM but squash your commits.

**Comment by saarthakchats** [comment]
@sarnava1 Done!

**Review by samagragupta — APPROVED** [review]

**Review by sarnava1 — APPROVED** [review]

**Comment by abishekvashok** [comment]
Ping @mariobehling, is this necessary?

**Comment by saarthakchats** [comment]
@abishekvashok What are we doing about this?

**Comment by saarthakchats** [comment]
Thank you! @mariobehling

**Pull request merged**
