### PR TITLE
UI/UX Design:Hover Effect Changed

### PR DESCRIPTION
**Pull request by bankebihariagrawal**
#756 
Issue Solved

### CODE REVIEW

**Comment by bankebihariagrawal** [comment]
The last Commit is the real commit and rest are reverted commit

**Comment by bankebihariagrawal** [comment]
Preview:

Before Change:

Before Change (1)

After Change:

After Change

I made changes in all files
Please Review This

**Review by Raunaksingh100 — COMMENTED** [review]
hi , plz attach the preview link..

**Comment by bankebihariagrawal** [comment]
Preview Link:

https://user-images.githubusercontent.com/52813916/87219429-ae8a1c00-c378-11ea-8ffd-dd8ff43ba92c.gif

Preview Gif:

After Change

**Comment by Raunaksingh100** [comment]
@bankebihariagrawal  
Preview link should show the improvements done on the website. The one mentioned in the PR description only shows the photo of the website. Kindly update it with a link that reflects the changes done. One way of doing that would be to host your site using any web-hosting services like surge or netlify

**Comment by bankebihariagrawal** [comment]
https://gifted-chandrasekhar-261bf8.netlify.app/

Please Check It, Sir

**Review by sparsh-99 — APPROVED** [review]

**Review by onkar-shaligram — APPROVED** [review]

**Review by dheerajkotwani — APPROVED** [review]

**Pull request closed without merging**
