### PR TITLE
Copyright position changed

### PR DESCRIPTION
**Pull request by Utkarshn10**

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
@Utkarshn10 Provide the proper description in pr what you fixed

**Comment by Utkarshn10** [comment]
@Raunaksingh100 I am new to this so could you please guide me how to generate a pr

**Review by vsasvipul0605 — COMMENTED** [review]
css changes are not required

**Comment by Utkarshn10** [comment]
@vsasvipul0605 Ok. Then i should revert the CSS changes and generate a pr

**Comment by Raunaksingh100** [comment]
@Utkarshn10 what is your purpose to create this pr??

**Comment by abishekvashok** [comment]
@Utkarshn instead of looking into this repo, can you please look in other active projects of fossasia such as open event? Eagerly waiting to see your contributions there.

**Comment by Utkarshn10** [comment]
> @utkarshn instead of looking into this repo, can you please look in other active projects of fossasia such as open event? Eagerly waiting to see your contributions there.

Yeah, sure.

**Comment by mariobehling** [comment]
no need

**Pull request closed without merging**
