### PR TITLE
Add a developer

### PR DESCRIPTION
**Pull request by akshit15013**
Description : Add a developer Mayank Vaidya to the Team section
Link to the website : https://akshit15013.github.io/fossasia123982.org/team/
Issue No. : #360 
screenshot 140

### CODE REVIEW

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, COULD YOU PLEASE MERGE IT?

**Comment by akshit15013** [comment]
@mariobehling @fragm3

**Review by sarnava1 — COMMENTED** [review]
LGTM

**Comment by akshit15013** [comment]
@YashKumarVerma @mariobehling @abishekvashok @jogendra

**Review by mariobehling — CHANGES_REQUESTED** [review]
The photo is not suitable for the official FOSSASIA Website.

**Comment by akshit15013** [comment]
@YashKumarVerma @mariobehling @abishekvashok @jogendra

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, COULD YOU PLEASE MERGE IT?

**Comment by akshit15013** [comment]
@YashKumarVerma @mariobehling @abishekvashok @jogendra

**Comment by akshit15013** [comment]
I have made the required changes in my PR.
Please merge it...

**Comment by akshit15013** [comment]
@mariobehling

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
