### PR TITLE
img/VibhorVerma.jpg: Change image size

### PR DESCRIPTION
**Pull request by sagar-kalra**
Change image size to match other images.

Fixes https://github.com/fossasia/fossasia.org/issues/171

### CODE REVIEW

**Comment by isuruAb** [comment]
@sagar-kalra  hi , it is already fixed please check the issue again 👍

**Comment by vibhcool** [comment]
I guess this issue is solved. Please mention in the issue if you are solving it in future. :)

Also check if other images are in right size. mention in the issue if you are working.

Cheers!!

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by vibhcool** [comment]
@mariobehling , this issue is resolved, 😅 . This PR can't be merged

**Pull request closed without merging**
