### PR TITLE
Reimplement slider for the blogcase section

### PR DESCRIPTION
**Pull request by vaibsharma**
@mariobehling Reimplement slider , this time I have not changed the existing css and js rather added latest css and js which were not present earlier ,for now  its perfectly working on my server 
screenshot from 2016-08-31 10 02 54
screenshot from 2016-08-31 10 03 09
screenshot from 2016-08-31 10 03 14

### CODE REVIEW

**Comment by mariobehling** [comment]
Could you let me know the link, where it is working, please? Tested on this site: https://vaibsharma.github.io/fossasia/ Does not seem to work here.

**Comment by vaibsharma** [comment]
https://vaibsharma.github.io/testing/ : this would work

**Comment by vaibsharma** [comment]
https://vaibsharma.github.io/fossasia/ @mariobehling  this would work

**Comment by mariobehling** [comment]
Thank you. Please check the following:
- [ ] Links often are missing a space before or after the words linked
- [ ] The "Read More" Link should use the existing css

screenshot from 2016-08-31 23 57 57

**Comment by vaibsharma** [comment]
@mariobehling last issue resolved .

**Comment by vaibsharma** [comment]
content problem solved + link problem solved + read more (Now continue reading with topic name) solved too .

**Comment by mariobehling** [comment]
Nice work!

**Comment by mariobehling** [comment]
I tried it on your side, but when hosted on fossasia.org there are still issues. not possible to swipe left and right..

**Comment by vaibsharma** [comment]
Okkay ! I just made PR #52 ! Please check , I think this time it should work fine !
Thanks

**Pull request merged**
