### PR TITLE
feat : Images need a proper alignment #690

### PR DESCRIPTION
**Pull request by aman-earthian**
I have added css property to modify "img-responsive" class in css/custom.css to solve the issue #690

### CODE REVIEW

**Review by Chaitanyassr — CHANGES_REQUESTED** [review]
Please provide a deployed link.

**Comment by aman-earthian** [comment]
> 
> 
> Please provide a deployed link.

Sorry, I am a  newbie and don't know what do you mean by deployed link.

**Comment by Chaitanyassr** [comment]
> > Please provide a deployed link.
> 
> Sorry, I am a newbie and don't know what do you mean by deployed link.

Hi @aman-earthian , Deployments are requests to deploy a specific ref (branch, SHA, tag). Deployed link are like prototype of the site. You can deploy site using netlify etc or by using GitHub also. In GitHub, You can find your deployed link by clicking on the environment in your repo. you can find the option besides commit,branch,package optn.

**Comment by aman-earthian** [comment]
> 
> 
> Please provide a deployed link.

https://hopeful-dijkstra-003ab4.netlify.app/

**Review by tikhsuP — CHANGES_REQUESTED** [review]
@aman-earthian 
Right now you have assigned `margin: auto;` to a particular class (img-responsive) and this has solved the problem to some extent, but, all the images that need to be aligned correctly do not follow this class.
Check out the **FOSSASIA Activities** section on the website.

 We should try to assign this margin to the img tag itself.

### What is happening:
foaaa

### What should happen: 
foa

**Comment by aman-earthian** [comment]
> 
> 
> @aman-earthian
> Right now you have assigned `margin: auto;` to a particular class (img-responsive) and this has solved the problem to some extent, but, all the images that need to be aligned correctly do not follow this class.
> Check out the **FOSSASIA Activities** section on the website.
> 
> We should try to assign this margin to the img tag itself.
> ### What is happening:
> 
> foaaa
> ### What should happen:
> 
> foa

check it now

**Review by tikhsuP — APPROVED** [review]
Looks good to me.

**Review by Raunaksingh100 — APPROVED** [review]

**Comment by mariobehling** [comment]
Current implementation is sufficient. Therefore closing it.

**Pull request closed without merging**
