### PR TITLE
Updated flexslider.css

### PR DESCRIPTION
**Pull request by JaiParakh**
Changed the z-index of .flex-control-nav  from 10 to 5.
Solved issue #466
vlcrecord2019030122h36m36s

Preview Link: https://jaiparakh.github.io/fossasia.org/

### CODE REVIEW

**Review by yash-kedia — APPROVED** [review]
pls provide a preview link

**Review by pranav1698 — COMMENTED** [review]
@JaiParakh this will require a preview link to test your changes, 
You can use surge or gh-pages for the same

**Comment by mariobehling** [comment]
Please provide a test deployment on your github pages.

**Review by championpaddler — CHANGES_REQUESTED** [review]
@JaiParakh 
Deploy pr on github pages for testing.

**Comment by JaiParakh** [comment]
Added the preview link of the repository. kindly review it and merge.

**Comment by yash-kedia** [comment]
@mariobehling the issue is solved

**Review by Ritzing — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Changes should be implemented on all pages in this repo. CNAME should not be changed. It will result in the site not being accessible anymore.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
