### PR TITLE
solved issue Add links to blog section and expand length of section to include more content bug #146

### PR DESCRIPTION
**Pull request by kartiktyagi4282**
solves the bug ----Add links to blog section and expand length of section to include more content bug
#146 opened on Aug 5 by mariobehling

### CODE REVIEW

**Comment by kartiktyagi4282** [comment]
@mariobehling , @isuruAb  can you review my fixes
before blog section is hiding in the corousel
before
and after fixing the bug it is looking like this.  
after

**Review by isuruAb — COMMENTED** [review]
hello @kartiktyagi4282. it seems you have fixed that 👍  , but it is bit hard to review this by checking screenshots. please add a preview link to the PR.
cheers 👍

**Comment by kartiktyagi4282** [comment]
here is the preview link ->   #199

**Comment by kartiktyagi4282** [comment]
@isuruAb  sir , here is the review link ->  #199 [file:///C:/Users/TYAGI/Downloads/fossasia.org-gh-pages/fossasia.org-gh-pages/index.html](url)

**Comment by kartiktyagi4282** [comment]
[fossasia.org/index-edit.html](url)

**Comment by kartiktyagi4282** [comment]
@isuruAb  sir i am newbie to these things. it will be grateful if you guide me how to provide review link
thanks..

**Comment by kartiktyagi4282** [comment]
@isuruAb  sir, here is the review link https://rawgit.com/kartiktyagi4282/fossasia.org/patch-2/index.html

**Pull request merged**
