### PR TITLE
Add and update more social profile

### LINKED ISSUE #651: Add more social icon
I want to add Weibo,Vk, Linkedin to the dropdown menu in the website.

### PR DESCRIPTION
**Pull request by hoangdatngo**
Fixed: #651 
## Purpose
Add Weibo, Vk, Linkedin icon to the dropdown menu in the website.
## Preview:
fossasia

The review link: https://hoangdatngo.github.io/fossasia.org/

Can @mariobehling, @hpdang, @kushthedude please review and merge my PR?

### CODE REVIEW

**Comment by prateekj117** [comment]
@hoangdatngo Review link is of another repo. What exactly are you trying to do here? Does this PR concern this repo?

**Comment by hoangdatngo** [comment]
@prateekj117 I have change my review link. I feel I'm a stupid right now. Can you please review and merge my PR. Sorry for wasting your time.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Not seeing the linked in icon on mobile. Can you please check?

**Comment by hoangdatngo** [comment]
@mariobehling Can you please review and merge it?

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
