### PR TITLE
chore: Remove duplicate team members

### LINKED ISSUE #786: Team member added twice in the Fossasia Team section
There is a team member 'Abhinav Raj' who is added twice in the team section on the website.
https://fossasia.org/team/

Find the more about the issue in the following screenshots.
Screenshot 2020-09-08 at 10 33 24 PM
Screenshot 2020-09-08 at 10 33 28 PM

### PR DESCRIPTION
**Pull request by pnijhara**
fix #786

Now the details of team member "Abhinav Raj" are shown only one time with this PR

Screenshot 2020-09-09 at 12 00 29 AM

### CODE REVIEW

**Comment by pnijhara** [comment]
cc @mariobehling

**Review by Raunaksingh100 — COMMENTED** [review]
@pnijhara first you update your pr as well as issue "description" so can i understand what you fixed in this pr
and also provide the screenshots

**Comment by pnijhara** [comment]
@Raunaksingh100 please check the issue description!
I have updated it.

**Review by prateekj117 — APPROVED** [review]
@iamareebjamal LGTM.

**Comment by iamareebjamal** [comment]
Praveen Ojha is repeated as well

**Comment by pnijhara** [comment]
Got it!
~Fixing that as well.~

@iamareebjamal fixed!

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
