### PR TITLE
Add docker icon to the footer

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
# Purpose 
The purpose of this PR is to add the docker icon to the footer of the relevant pages.
Issue: #576 

# Approach
- Update font awesome to the latest version. (Because in the current version docker icon is missing).
- Add docker icon to the footer of relevant pages.

# Preview 
https://kumuditha-udayanga.github.io/fossasia.org/

# Screenshot

Screenshot 2019-12-29 at 22 54 46

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
@mariobehling It would be great to have your reviews.. :)

**Comment by Dishebh** [comment]
@kumuditha-udayanga I guess there's an issue open for it. You can refer it in your description above. Thanks.

**Comment by kumuditha-udayanga** [comment]
> @kumuditha-udayanga I guess there's an issue open for it. You can refer it in your description above. Thanks.

Sure thank you 😇

**Review by kushthedude — CHANGES_REQUESTED** [review]
Revert all changes other than the one you are doing

**Review by NishithP2004 — APPROVED** [review]
LGTM (the icon)

**Comment by NishithP2004** [comment]
> Revert all changes other than the one you are doing

Please have this done as well

**Review by mariobehling — CHANGES_REQUESTED** [review]
There are lots of unrelated changes. Please only change things related to the docker image.

**Comment by kumuditha-udayanga** [comment]
@mariobehling this PR will be closed docker icon was added recently.

**Pull request closed without merging**
