### PR TITLE
different popup images issue corrected

### LINKED ISSUE #664: On click different image popup.
### In Memories from FOSSASIA Events section different image popup when clicked on an image for it's preview.
As screenshot attached image with Red line have this issue.

fossasia issue

@mariobehling is this a valid issue?

**If so,I would like to work on it.**

### PR DESCRIPTION
**Pull request by Sohan022**
On clicking, different images popup in memories section of FOSSASIA  corrected

fixed: #664

### CODE REVIEW

**Review by mohitm15 — CHANGES_REQUESTED** [review]
Please attach a preview link

**Comment by Sohan022** [comment]
> Please attach a preview link

https://sohan022.github.io/fossasia.org/

**Review by Chaitanyassr — APPROVED** [review]

**Comment by Sohan022** [comment]
please merge

**Comment by Chaitanyassr** [comment]
Please squash the commit

**Comment by Sohan022** [comment]
I'm creating a new pull request due to some mistake in this branch of the repo.

**Comment by Chaitanyassr** [comment]
Hi @sohan022 close the old one.

**Review by Raunaksingh100 — APPROVED** [review]

**Comment by mariobehling** [comment]
Missing details, missing screenshots. Therefore closing it.

**Pull request closed without merging**
