### PR TITLE
Added mentors

### PR DESCRIPTION
**Pull request by mhlee304**
Update team.html
Update team.html
Update team.html
Preview of website: https://mhlee304.github.io/fossasia.org/team

### CODE REVIEW

**Comment by anshumanv** [comment]
Resolve conflicts please.

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
LGTM! Please resolve conflicts

**Comment by abishekvashok** [comment]
Resolve the conflicts and this is ready to go

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@mhlee304  Please add all at members the last of the `Developers` section not at starting and resolve conflicts 👍

**Review by akshatnitd — CHANGES_REQUESTED** [review]
@mhlee304 Please add all at members the last of the Developers section and not at the starting, as suggested by @ParthS007 :+1:

**Review by nikit19 — CHANGES_REQUESTED** [review]
@mhlee304  I am an Android developer and why are you not adding the social links of the developers?

**Comment by ParthS007** [comment]
closing this PR, @mhlee304  Please create a new PR considering all the changes suggested by other mentors. Thanks

**Pull request closed without merging**
