### PR TITLE
Fixed the non-uniformity in the buttons of  Background and Missions page.

### PR DESCRIPTION
**Pull request by siddhantshukla-10**
Fixed the non-uniformity of Background and Missions page
Please review the pull request.

### CODE REVIEW

**Comment by siddhantshukla-10** [comment]
Normal View
screenshot from 2018-10-02 10-58-18

**On hover**
screenshot from 2018-10-02 10-58-41

**Comment by siddhantshukla-10** [comment]
@mariobehling @abishekvashok please review this pull request

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Please provide a preview link

**Review by samagragupta — COMMENTED** [review]
Looks fine 👍 
Just provide the Deployment link.

**Comment by mariobehling** [comment]
closing due to inactivity.

**Pull request closed without merging**
