### PR TITLE
Fixes: #152 header moving bug fix

### PR DESCRIPTION
**Pull request by AshishkrGoyal**
Fixes: #152 
@mariobehling sir..
please review this pull request

Thanks in advance 😄

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
could you please provide a preview link ?

**Comment by AshishkrGoyal** [comment]
@isuruAb 
please visit this link for preview:

http://www.ashishkrgoyal.me/fossasia.org/

**Review by isuruAb — APPROVED** [review]
nice 👍 
please read this blog post about best practices.
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by AshishkrGoyal** [comment]
@isuruAb 
Thank You Very Much For Your Support ❤️

**Pull request merged**
