### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Devansh3712**
Added link to docker

### CODE REVIEW

**Review by kushthedude — APPROVED** [review]

**Review by RohitRathore1 — APPROVED** [review]

**Review by mohitm15 — APPROVED** [review]

**Comment by NishithP2004** [comment]
Please provide a preview link.

**Comment by Devansh3712** [comment]
@NishithP2004 where to find it?

**Comment by NishithP2004** [comment]
I mean the username.GitHub.io/repo link to preview someone's work

**Comment by Devansh3712** [comment]
Ohh, here it is: Devansh3712.GitHub.io/fossasia.org

**Comment by Devansh3712** [comment]
http://devansh3712.github.io/fossasia.org/

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
The icon isn't loading .
Please refer your preview link.

**Comment by NishithP2004** [comment]
That's the issue here, Crunchbase isn't available in the Font awesome library.

**Comment by Devansh3712** [comment]
So what should I do?

**Review by Devansh3712 — COMMENTED** [review]
Added link to docker instead of crunchbase

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
I believe that the page already had all the icons but was removed for some reason.

**Review by mohitm15 — COMMENTED** [review]
Please attach the issue you solved via this PR

**Pull request closed without merging**
