### PR TITLE
chore: Fix dimension of images, add title overlay and Play Store and F-Droid badges

### LINKED ISSUE #526: Improve Mobile App Section
Provide more relevant screens showing more of the main feature of the apps in the bottom row. Image size should be Width: 364 x Height: 647

Screenshot from 2019-08-10 05-26-17

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #526 and #527 

Changes:

- Updated images to use the recent ones.
- Updated dimensions of all images. (364 x 647)
- Added title overlay for images.
- Added Play Store and F-Droid badges.

Link for testing: https://shridhargoel.github.io/fossasia.org/

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please ensure that all screenshots of apps have the same width x height. Don't squeeze them or stretch them. Part of this issue to ensure they all have the same dimensions. Please ensure the following images have the same width x height and list it in the PR description. One main goal of the issue to ensure conformity across app images:
* SUSI.AI-Android.jpg W ?? x H ??
* PSLab_Android.jpg W ?? x H ??
* Phimpme_android.jpg W ?? x H ??
* Eventyay_Organizer_Android.jpg W ?? x H ??
* Eventyay_Attendee_Android.jpg W ?? x H ??
* Badge_Magic_Android.jpg W ?? x H ??

**Comment by mariobehling** [comment]
Provide a test page. Follow best practices always!

**Comment by mariobehling** [comment]
Please take care of the whole issue instead of bit-sizing it: https://github.com/fossasia/fossasia.org/issues/527

**Comment by ShridharGoel** [comment]
@mariobehling Updated.

**Comment by mariobehling** [comment]
* Please don't change the space used by the images. Things should not appear bigger. Keep some space as of now.
Screenshot from 2019-08-14 16-30-09

* Gray area on bottom of images is not aligned with images
Screenshot from 2019-08-14 16-27-35
* Please add Github badge. We discussed adding Github in the meetings, but I missed adding it into the issue. Please add it as a badge. Thanks!

**Comment by mariobehling** [comment]
Please also make the overlay gray a bit darker. The info is difficult to read.

**Comment by ShridharGoel** [comment]
@mariobehling Updated, please have a look. Where should the GitHub badge be added, next to the Play Store and F-Droid badges?

**Comment by mariobehling** [comment]
> @mariobehling Updated, please have a look. Where should the GitHub badge be added, next to the Play Store and F-Droid badges?

* Add Github Badge next to Android badges. Reduce the size of the badge, so they fit all below the screenshot.
* Reduce the transparency of the overlay area. Names are not readable.

**Comment by ShridharGoel** [comment]
@mariobehling Updated.

**Comment by ShridharGoel** [comment]
Also made the text darker so that it is easily readable.

**Comment by kushthedude** [comment]
@ShridharGoel All the photos are pixelating, Can you increase the resolution a bit so that they don't pixelate.
Also please resolve this, Makes UI look really bad.
image

**Comment by mariobehling** [comment]
@ShridharGoel Please provide a non-pixelated resolution and an actual Github Badge. All three Playstore, Fdroid, Github badges should have the same size.

**Comment by mariobehling** [comment]
Merging this as WIP. @ShridharGoel Please finalize the points mentioned here.

**Comment by ShridharGoel** [comment]
@mariobehling On it.

**Comment by abishekvashok** [comment]
@ShridharGoel any updates on this?

**Pull request merged**
