### PR TITLE
Listed items in order

### PR DESCRIPTION
**Pull request by vaibsharma**
Placed items in the correct ordered sequence in the listed column .

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@vaibsharma Thanks for your contribution.

Kindly squash commits in this PR.

Also, check out more projects like Loklak, AskSUSI and OpenEvent which require more contributors' insight.

Cheers 👍

**Comment by mariobehling** [comment]
What is the issue for this pull request? What are you changing? Screenshot?

**Comment by vaibsharma** [comment]
@mariobehling I am attaching the screenshot . 
screenshot from 2016-08-04 21 46 40
screenshot from 2016-08-04 21 47 25

**Comment by mariobehling** [comment]
I am not sure, if we need those minor modifications. What we really need is someone who helps to solve some larger issues. If you are interested e.g. this one https://github.com/fossasia/fossasia.org/issues/41

**Comment by vaibsharma** [comment]
@mariobehling Okay sir I will soon make a PR once I am done .
Thanks

**Comment by vaibsharma** [comment]
for issue #41  
@mariobehling ,hello sir , Sorry being absent for that long , from yesterday I started with this issue and for now I have been quite successful in getting .
1. Automatically show the last 10 blog entries of the FOSSASIA blog
2. Include heading, and below only show the first two paragraphs and a read more link
3. Use the xml file of http://blog.fossasia.org/feed/ 
Could you please give me the type of styling that is required in the blog section for the dispaly and also what images and which links you are referring in 4th implementation.

Thank you 
best regards
Vaibhav Sharma

**Pull request closed without merging**
