### PR TITLE
Added favicon to Team, licenses and donate pages

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Added favicon to Team, Donate and License Page
I modified the link urls in each index file from `http://` to `https://`

### CODE REVIEW

**Review by sarnava1 — COMMENTED** [review]
Hello @BolajiAyodeji please fill the PR template properly and squash your commits. Also provide a preview link or provide screenshots showing the changes. Thank you.

**Comment by BolajiAyodeji** [comment]
Fixed grid columns bug in Team page

## Before
image

## After
image

**Comment by BolajiAyodeji** [comment]
@sarnava1 where can I get the PR template?
I didn't see any?

**Comment by BolajiAyodeji** [comment]
Here is the preview link to all my changes
https://bolajiayodeji.github.io/fossasia.org-bolaji/team/

Here is a breakdown of all my changes;
- Added favicon to team, license and donate page
- Modified links url from http: to https: in all pages
- Fixed grid column bug in Team page for desktop view
@sarnava1 @jogendra

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
