### PR TITLE
issue No gap between the icons in hamburger menu #654 solve

### PR DESCRIPTION
**Pull request by keshavagarwal17**
make gap between the icons in hamburger menu

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please don't edit theme files. Instead try to use existing classes to fix the issues. If it is still not possible then only fallback to custom css (it should be in custom.css). Modifying theme files will have unintended consequences and is not recommended

**Comment by keshavagarwal17** [comment]
oh sorry, I don't know that thing. Ok i will change in custom.css file and than i will do PR.

**Comment by keshavagarwal17** [comment]
@abishekvashok  actually theme-lava.css has a margin-right property, which is overriding when i change this property from custom.css for the gap. To change this property i have to make changes on theme-lava.css.

**Review by Raunaksingh100 — COMMENTED** [review]
plz  provide the delpoy link or preview link??

**Comment by mariobehling** [comment]
Missing details, missing screenshots. Therefore closing it.

**Pull request closed without merging**
