### PR TITLE
change membership size so that it won't overlap.(issue #627)

### PR DESCRIPTION
**Pull request by Chaitanyassr**
deployed link - https://chaitanyassr.github.io/fossasia.org/

before - 
Screenshot (127)

after - 
Screenshot (132)

### CODE REVIEW

**Comment by Chaitanyassr** [comment]
@mariobehling Sir, i opened an issue 
#627 about the membership overlapping the text. here is the fix for it. please check

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please change the CSS of "Price" to this size instead of adding more and more into the html code.

**Comment by Chaitanyassr** [comment]
> Please change the CSS of "Price" to this size instead of adding more and more into the html code.

Done, i have changed the font-size in every theme css to make the changes take effect.
please check - https://chaitanyassr.github.io/fossasia.org/

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Thanks!

**Comment by Chaitanyassr** [comment]
> Thanks!

you're welcome sir.

**Pull request merged**
