### PR TITLE
Update About FOSSASIA Footer text in all web pages #453 

### PR DESCRIPTION
**Pull request by khan0604**
Issue #453

Created a "footer.html" file for all the footer contents and the footer of all the files are loaded from "footer.html" file. In this way, if footer needs to be updated again in the future only one file "footer.html" will be needed to change and the changes will be reflected in all the files.

### CODE REVIEW

**Comment by khan0604** [comment]
@mariobehling here is the preview link : https://fossasia0604.000webhostapp.com/

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
Please provide hyperlinks in the about for Mario Behling,Hong Phuc Dang and Codeheat.

**Comment by khan0604** [comment]
@NishithP2004 I have added the hyperlinks as stated in the issue. Please review my changes.

**Review by plxity — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. Good ideas with the footer.html. How can we get this without adding external dependencies to jquery.com and googleapis? We actually want to decrease dependencies instead of increasing them. We don't want to share our user's data with external services.

**Comment by khan0604** [comment]
@mariobehling The another way this can be achieved is using PHP code
<?php include('footer.php'); ?> 
but that will require changing "footer.html" to "footer.php" and all the "index.html" to "index.php" . Do you want me to do the following changes?

**Comment by khan0604** [comment]
@mariobehling he another way this can be achieved is using PHP code
 `<?php include('footer.php'); ?>`
but that will require changing "footer.html" to "footer.php" and all the "index.html" to "index.php" . Do you want me to do the following changes?

**Comment by khan0604** [comment]
@mariobehling The another way this can be achieved is using PHP code
`<?php include('footer.php'); ?>`
but that will require changing "footer.html" to "footer.php" and all the "index.html" to "index.php" . Do you want me to do the following changes?

**Comment by mariobehling** [comment]
Everything needs to work on Github pages. PHP does not.

**Comment by khan0604** [comment]
@mariobehling Google APIs were already in use in the codebase. I did not add it.
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" ></script>`

I only added one jquery script.
`<script src="//code.jquery.com/jquery-1.10.2.js"></script>`

There is no other way ( except the two ways I mentioned one using jquery script and other using php) to load the contents of "footer.html" in all the files. 

The only way left is just changing the footer content of all the files without creating any "footer.html" file. Please suggest me what to do next.

**Comment by khan0604** [comment]
@mariobehling If you don't want just one more dependency then should I just simply change the footer content of all the files without creating any "footer.html" file?

**Pull request closed without merging**
