### PR TITLE
enh: adding description of apps and adding overlay effect

### LINKED ISSUE #527: Add info area with expanding image title overlay effect on top of Android app screenshots
Please implement a simple dark gray overlay on the bottom (a square covering the bottom of the image). Avoid Gradients. Compare the general effect here: https://www.w3schools.com/howto/howto_css_image_overlay_title.asp

Only add one effect that moves up from the bottom and include 
* Name of app
* One Scroll-over show: Short description of the app. **Please make the effect in the way that the bottom gray bar expands from bottom to 2/3 of the app image - like make it moving in from the bottom with the description, please.**

Below the app screenshot please add a badge for a) Playstore and b) Fdroid.

screenshot from 2019-01-02 15-05-23

This issue is free to take up for anyone.

### PR DESCRIPTION
**Pull request by maze-runnar**
fixes :  #527
adding short description of apps from google play store and implementing overlay effect on hover . 
ezgif com-gif-maker (4)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please change the effect in the way that the bottom gray bar expands from bottom to 2/3 of the app image - like make it moving in from the bottom with the description, please.

**Comment by maze-runnar** [comment]
Ok

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Comment by maze-runnar** [comment]
@mariobehling my end sem exams are currently running , that's why i was inactive . i will be free by 20 . I was planning to finish it on that day .

**Comment by maze-runnar** [comment]
@mariobehling please reopen it i will make chnages till 21 .

**Pull request closed without merging**
