### PR TITLE
Fixes #64 : changes classes in the footer section to fix the navbar crash

### LINKED ISSUE #64: Navbar Crash for Ipad Portrait Orientation
The Navbar's Hamburger Button does not appear fully for ipad portrait mode ( 768 px \* 1024 px ) @mariobehling @the-dagger

### PR DESCRIPTION
**Pull request by Shivang-Bhandari**
Changed Classes in footer of index.html at line no. 989 and 995 to make resolve the fix.
h

### CODE REVIEW

**Comment by Shivang-Bhandari** [comment]
Can be previewed on the following link :- 

https://shivang-bhandari.github.io/fossasia.org/

**Comment by daminisatya** [comment]
@Shivang-Bhandari Please give a commit message as in what change you had made. please follow the format `Fixes #<issue number> : <commit message>`

**Comment by Shivang-Bhandari** [comment]
@daminisatya Done

**Comment by daminisatya** [comment]
@Shivang-Bhandari Look at the description. That's how the title and commit should be maintained

**Comment by Shivang-Bhandari** [comment]
@daminisatya Thank You so much ill make sure to follow the guidelines in future.

**Comment by mariobehling** [comment]
This pull request is not matched with an issue and I do not know which issue is there with the nav bar crash. Where is the issue? 

The result of this PR is that the width distribution of the bottom fields is changed and it should have been changed. So, I am reverting this.

**Pull request merged**
