### PR TITLE
Added mentor

### PR DESCRIPTION
**Pull request by arihantbansal**
* Added mentor Sridhar Jajoo to the team page

View changes at https://arihantbansal.github.io/fossasia.org/team/

newsnip

### CODE REVIEW

**Review by jogendra — CHANGES_REQUESTED** [review]
Please make it more suitable to fossasia website like close look.

**Comment by arihantbansal** [comment]
Sorry, I didn't quite understand. Can you please explain again?

**Comment by meets2tarun** [comment]
Hi @arihantbansal 
Please make the image look similar to other images which are already there.

Did you get the point?

**Comment by arihantbansal** [comment]
Updated 
news

**Comment by jogendra** [comment]
@arihantbansal It becomes blurred, please ask  **Sridhar** for better quality image

**Comment by arihantbansal** [comment]
@jogendra, I've asked him.

**Comment by arihantbansal** [comment]
I've changed the image. Please merge.

**Review by jogendra — CHANGES_REQUESTED** [review]
Please use **Square** image (1:1 ratio)

**Comment by arihantbansal** [comment]
Sorry for the delay. I've changed the image dimensions.

**Comment by mariobehling** [comment]
250px is mininmum.

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
The image is still blurred.Please change it.

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
Please resolve the conflicts as well.I would suggest taking his image from his GitHub and changing the image to the required ‘250x250px’ as said earlier.

**Comment by NishithP2004** [comment]
‘’250’’

**Comment by arihantbansal** [comment]
Done.

**Review by NishithP2004 — APPROVED** [review]
@jogendra Requesting a review.The image looks a bit better now.

**Comment by mariobehling** [comment]
This picture is not scaled according to proportion. I am closing this issue now. We need to be more efficient with our PRs and cannot spend too much time on this. From now on mentors should take responsibility themselves for adding their image and details to the website. Thanks for learning about this! Hope you continue to contribute. Cheers.

**Pull request closed without merging**
