### PR TITLE
Update index.html

### LINKED ISSUE #453: Update About FOSSASIA Footer text
Please update the footer text as follow:

FOSSASIA develops Open Source software and hardware solutions with a global developer community from its base in Asia and organizes [Open Technology events](https://events.fossasia.org) around the year. The mission of FOSSASIA is to improve people's lives by sharing open technologies, knowledge and resources and building a sustainable FOSS ecosystem. Projects include [conversational AIs](https://susi.ai), [science applications](https://pslab.io) and [event management tools](https://eventyay.com). The organization supports its most promising teams through a business incubator and runs coding programs and development contests like [Codeheat](https://codeheat.org/) to grow the developer community. FOSSASIA's annual [OpenTechSummit](https://fossasia.sg/) in Singapore is the premier Open Technology event in Asia for developers, tech companies, and contributors. FOSSASIA was founded in 2009 by [Mario Behling](https://twitter.com/mariobehling) and [Hong Phuc Dang](https://twitter.com/hpdang).

### PR DESCRIPTION
**Pull request by NishithP2004**
Fixes #453

### CODE REVIEW

**Review by plxity — CHANGES_REQUESTED** [review]
Please provide a preview link.

**Comment by NishithP2004** [comment]
I’m not able to create a preview link. @plxity

**Review by plxity — CHANGES_REQUESTED** [review]
Okay, But you have not added website links to codeheat ,OpenTechSummit and etc. Make sure to add them.

**Comment by mariobehling** [comment]
Please change also change text on about, team etc. (all pages).

**Comment by NishithP2004** [comment]
@mariobehling Please review, do I need to update it anywhere else.Please state.

**Comment by mariobehling** [comment]
all pages

**Comment by NishithP2004** [comment]
@mariobehling But is the matter correct so that I can reproduce it in the other places.

**Comment by mariobehling** [comment]
All pages should be updated.

**Pull request closed without merging**
