### PR TITLE
Added missing icons as per #616

### PR DESCRIPTION
**Pull request by prashant5878-shukla**
#616  add more profile Links
Preview link:https://coder135792468.github.io/fossasia.org/

### CODE REVIEW

**Comment by coder135792468** [comment]
#625 added more profile Links

**Comment by NishithP2004** [comment]
Please provide a preview link.

**Comment by prashant5878-shukla** [comment]
Here is the preview link

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
This PR is invalid as Google + is extinct.

**Comment by prashant5878-shukla** [comment]
Okk

**Pull request closed without merging**
