### PR TITLE
Fixed the alignment of section-header

### PR DESCRIPTION
**Pull request by Dishebh**
Fix issue #637 

Fixed the alignment of section,

### Screenshot of the result:
Screenshot from 2020-01-08 23-53-36

[Test link](http://dishebh.github.io/fossasia..org)

### CODE REVIEW

**Review by Chaitanyassr — COMMENTED** [review]
Please provide a deployed link. the link given is not working.

**Comment by Dishebh** [comment]
Test Link:
https://dishebh.github.io/fossasia.org/

Here it is: @Chaitanyassr

**Review by Chaitanyassr — CHANGES_REQUESTED** [review]
there has been few major and minor merges before and the deployed link is not showing them. Please also add those merges into your PR.

**Review by Chaitanyassr — CHANGES_REQUESTED** [review]
please check ones.

**Comment by Dishebh** [comment]
@Chaitanyassr how about now?
Test link: 
https://dishebh.github.io/fossasia.org/

**Review by Chaitanyassr — APPROVED** [review]
please squash the commit, 
looks greate , it has all the changes @mariobehling please check.

**Review by mohitm15 — CHANGES_REQUESTED** [review]
Please squash your commits

**Comment by Dishebh** [comment]
@Chaitanyassr @mohitm15 since there are too many commits diverging, I opened a new PR with changes done and the branch updated the default gh-pages branch of fossasia.org. 
PR #658

**Pull request closed without merging**
