### PR TITLE
added fixes to broken links #531

### LINKED ISSUE #531: Page fossasia.org/coc/index.html broken due to wrong CSS links
THe page fossasia.org/coc/index.html is broken as links and images are linked in another directory. Please help to fix it.

### PR DESCRIPTION
**Pull request by Yachitha**
Fixes #531 

Preview: https://yachitha.github.io/fossasia.org/coc/index.html

I've added fixes to broken links if there is any issue in the pull request please comment and I'll check them out.

### CODE REVIEW

**Review by liveHarshit — COMMENTED** [review]
Please provide a preview URL.

**Comment by Yachitha** [comment]
Image 1

### check this screenshot

**Comment by Yachitha** [comment]
@liveHarshit check the preview image, do I need to host this? I mean in github pages?

**Comment by liveHarshit** [comment]
> @liveHarshit check the preview image, do I need to host this? I mean in github pages?

It will be better if you provide the URL.

**Comment by Yachitha** [comment]
Okay, please give me a moment.

**Comment by Yachitha** [comment]
https://yachitha.github.io/fossasia.org/coc/index.html
please check this URL.

**Comment by liveHarshit** [comment]
> https://yachitha.github.io/fossasia.org/coc/index.html
> please check this URL.

Please fix the background also:
image

**Comment by Yachitha** [comment]
Image 2
according to inspection I have done the background image set to be display none by css. Do I need to change this?

**Comment by liveHarshit** [comment]
@Yachitha But the white text on a white background is really looking weird, do you agree with that? Can you fix this also?

**Comment by Yachitha** [comment]
@liveHarshit yeah sure. I'll fix it. Yeah it's not good to have white background. I'm totally agree with you.

**Comment by mariobehling** [comment]
@Yachitha You dont need to change a lot. Just link the correct images and css. Compare to http://coc.fossasia.org/index1.html
https://github.com/fossasia/coc.fossasia.org/blob/gh-pages/index1.html
Thanks

**Comment by mariobehling** [comment]
Please also change the top menu bar to the same as on the main page. Ensure links to the repo itself are using relative links "./..." instead of https://fossasia.org/somelink...

**Comment by Yachitha** [comment]
sure I'll check these things out please give me some time to clarify these things.

**Comment by Yachitha** [comment]
@liveHarshit @mariobehling guys please check this now and comment on it for any changes.
https://yachitha.github.io/fossasia.org/coc/index.html

**Review by liveHarshit — APPROVED** [review]
Thanks

**Comment by mariobehling** [comment]
The links on the top menu arenot changed in the same way as in the main page, but I merge this as work in progress.

**Review by mariobehling — COMMENTED** [review]
Oh, I missed this change in script.js. This should not be changed. It broke all other pages of the repo. Therefore reverting this PR. Please try to fix it without changing script.js.

**Comment by Yachitha** [comment]
@mariobehling ooh okay I'll try to do this whithout chainging the script.js and will check the menu bar as well.

**Pull request merged**
