### PR TITLE
adding self name to developers team section

### PR DESCRIPTION
**Pull request by rpotter12**
I am a collaborator of meilix-generator and GCI 2018 mentor at FOSSASIA.

### CODE REVIEW

**Review by jakubpawlina — APPROVED** [review]
LGTM

**Review by samagragupta — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please provide an image with no more than 40KB.

**Comment by rpotter12** [comment]
@mariobehling I have changed my image whose size is less than 40kb.
Please review it. :)

**Review by sarnava1 — APPROVED** [review]
LGTM

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
