### PR TITLE
Added Yaydoc to navbar

### LINKED ISSUE #639: Add yaydoc.org into dropdown menu on all FOSSASIA.org Github pages
Yaydoc is running on yaydoc.org. Please add the link to the FOSSASIA dropdown menu into the "projects" tab above "Meilix".

Screenshot from 2020-01-09 16-51-59

### PR DESCRIPTION
**Pull request by NishithP2004**
Hi, I have added Yaydoc to the drop-down in all the pages.
[Preview Link](https://nishithp.live/fossasia.org)
Fixes #639

### CODE REVIEW

**Comment by thewasif** [comment]
error
One item is coming out of the menu. This doesn't look good. Please fix it!

**Comment by NishithP2004** [comment]
May I know in which page this error is seen as I haven't encountered this
issue before.

**Comment by thewasif** [comment]
In home page, at the end of **Projects** tab

**Comment by NishithP2004** [comment]
> In home page, at the end of **Projects** tab

Could you please recheck as I'm not facing that issue.

**Comment by thewasif** [comment]
ezgif-2-f3e71dbddfa0
Look at the end of menu

**Comment by NishithP2004** [comment]
@mariobehling Please review

**Comment by NishithP2004** [comment]
@mariobehling @hpdang Please review.

**Comment by abishekvashok** [comment]
Screenshot from 2020-01-13 19-51-50
Text is overflowing out of the menu, please check.

**Pull request closed without merging**
