### PR TITLE
Added Team Member

### PR DESCRIPTION
**Pull request by NishithP2004**
I have added Prateek Jain as a team member to the site.
[Preview Link](https://nishithp.live/fossasia.org)

## Screenshots
Screenshot (30)

### CODE REVIEW

**Comment by dipu989** [comment]
@NishithP2004 Looks good! :+1:  Just squash the commits into one.

**Comment by NishithP2004** [comment]
> @NishithP2004 Looks good! 👍 Just squash the commits into one.

I’m unable to squash the commits

**Comment by NishithP2004** [comment]
@dipu989 Please review

**Review by liveHarshit — CHANGES_REQUESTED** [review]
How do you find Prateek Jain as a team member?

**Comment by NishithP2004** [comment]
His Description in his Portfolio,Twitter & GitHub pages says that he is a
Software Developer intern at Fossasia.

**Comment by NishithP2004** [comment]
@dipu989 Please review

**Comment by NishithP2004** [comment]
@mariobehling @hpdang Please review

**Review by liveHarshit — APPROVED** [review]

**Pull request merged**
