### PR TITLE
Improved navigation Panel for mobile view

### PR DESCRIPTION
**Pull request by s-pratyush**
BEFORE =>
Screen Shot 2020-05-10 at 19 35 10

NOW
Screen Shot 2020-05-10 at 19 37 39

### CODE REVIEW

**Review by Chaitanyassr — CHANGES_REQUESTED** [review]
Hi @Pratyush-Saxena now where is shop and blog? can you also proivde a deployed link?

**Comment by s-pratyush** [comment]
Sir all those links are in "other " link dropdown

**Comment by s-pratyush** [comment]
Even it also consist of donate and contact options which were earlier hidden

**Comment by s-pratyush** [comment]
@Chaitanyassr  any updates regarding my this PR?

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr any updates regarding my this PR?
Can you also provide a deployed link.

**Comment by Chaitanyassr** [comment]
Also this is a feature request so it would be better if the people incharge will review this PR @abishekvashok @mariobehling @prateekiiest

**Comment by s-pratyush** [comment]
Deployment link-
https://pratyush-saxena.github.io/Pratyush_saxena-fossasia.org/

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please properly intend the code

**Comment by mariobehling** [comment]
Current implementation is already sufficient.

**Pull request closed without merging**
