### PR TITLE
add hover effect to images of developed at fossasia section

### PR DESCRIPTION
**Pull request by Soumi150**
When cursor is hovered over an image, it's name will be displayed.
change

### CODE REVIEW

**Comment by Soumi150** [comment]
when cursor is hovered on image ,name of app will be displayed.Please review it
change

**Review by vsasvipul0605 — APPROVED** [review]

**Review by Raunaksingh100 — COMMENTED** [review]
hey , plz provide the preview link .............

**Comment by Soumi150** [comment]
preview link:   https://soumi150.github.io/fossasia.org/

**Comment by Soumi150** [comment]
Please review this @mariobehling .

**Comment by abishekvashok** [comment]
Hey I suggest, we look into much more issues on active projects such as eventyay

**Comment by mariobehling** [comment]
no need

**Pull request closed without merging**
