### PR TITLE
Added screenshots of android apps in index.html

### LINKED ISSUE #374: Add screenshots of Android apps into Android section instead of logos
The Android App section has logos to link to the app store at the moment. Please add large screenshots here instead.

screenshot from 2018-11-23 19-17-15

### PR DESCRIPTION
**Pull request by siddharthgusain**
1. fixes #374.
2.Added screenshots of android apps in index.html instead of logos
3. Before:-
before
4.After:-
after

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]

**Comment by mariobehling** [comment]
Thank you. Please provide a preview link.

**Comment by abishekvashok** [comment]
It must be https://siddharthgusain.github.io/fossasia.org

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Not working properly on mobile.

**Review by championpaddler — CHANGES_REQUESTED** [review]
@siddharthgusain  Screenshot section is not responsive. FIx that .

**Pull request closed without merging**
