### PR TITLE
Rectified dropdown menu's height

### PR DESCRIPTION
**Pull request by deprov447**
Changed the dropdown menu heights of nav-items :  Projects, Events, Programs and About to cover all drop-items.

### CODE REVIEW

**Comment by deprov447** [comment]
Issue #751 solved

**Review by liveHarshit — CHANGES_REQUESTED** [review]
Preview url?

**Comment by deprov447** [comment]
**Before :**
fossasia
**After :**
fossasia2

**Comment by onkar-shaligram** [comment]
@deprov447 It has been clearly written in the **index.html** file to go in **+-25px** manner So that there is some uniformity in the nav-dropdown lists. So you can do those changes & update the Pull Request accordingly.
@liveHarshit kindly have a look after the changes which I requested

**Comment by liveHarshit** [comment]
Please provide preview url with gh pages.

**Comment by deprov447** [comment]
sorry, @liveHarshit , It took me sometime to understand.
[Preview](https://deprov447.github.io/display_fossasia/)

**Review by liveHarshit — APPROVED** [review]

**Pull request merged**
