### PR TITLE
added maintainer ray

### PR DESCRIPTION
**Pull request by YashKumarVerma**
added a new team member.

https://github.com/rctay

Preview Link
https://yashkumarverma.github.io/fossasia.org/team

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@YashKumarVerma Please provide a preview link else LGTM

**Review by rupav — CHANGES_REQUESTED** [review]
Image added is empty. Preview link don't have image of the added developer. Rectify this.

**Review by isuruAb — COMMENTED** [review]
image is not working please check

**Review by mariobehling — CHANGES_REQUESTED** [review]
Image not loading.

**Comment by YashKumarVerma** [comment]
@mariobehling @rupav @ParthS007 
image updated

**Review by rupav — APPROVED** [review]
Great work @YashKumarVerma . Wait for 1 more approval to get it merged.

**Review by sayak119 — APPROVED** [review]
LGTM

**Comment by mariobehling** [comment]
This image is not suitable and it does not show the team member.

**Pull request merged**
