### PR TITLE
Solves & Fixes Issue No #30 | Instagram link added

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
Solves & Fixes Issue #30 . 
1. Instagram link added.

Please review this PR @jig08 . Please advise if any changes are required. 

Fixed Issue #30 .

Thanks. :smile:

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
@jig08 This doesn't have any conflicts with the base branch. So can this PR get merged?

Thanks! :)

**Comment by jigyasa-grover** [comment]
Tip: Always add a preview/demo link for an easier check.

**Comment by ashutoshsaboo** [comment]
Yup. Thanks @jig08 ! Here is the attached screenshot of `index.html` (The Instagram logo at the bottom has been added)-:

selection_002 

So, is this good to get merged now?

**Comment by jigyasa-grover** [comment]
Link means something like `<username>.github.io/fossasia.org` where the site is actually published

**Comment by ashutoshsaboo** [comment]
Umm Yes sure @jig08 . The modified `index.html` of the FossAsia website can be found at this URL - <a href="https://ashutoshsaboo.github.io/fossasia/index.html"> Link </a> . So, is this good to merge now?

**Comment by jigyasa-grover** [comment]
Good to go @ashutoshsaboo :)

**Comment by ashutoshsaboo** [comment]
@jig08 Thanks a lot maam! :)

**Pull request merged**
