### PR TITLE
[Solved - #474] Added back to top button

### PR DESCRIPTION
**Pull request by supunTE**
Added back to top button.
 Solved https://github.com/fossasia/fossasia.org/issues/474
image
https://stedirisuriya.github.io/stedirisuriya-fossasia.org/

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please use an icon like an up arrow (^) for the feature. Don't delete the CNAME.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Don't change gitignore. Use the same way to scroll up like the "top" links using the smooth scrolling effect.

**Comment by pkspyder007** [comment]
@mariobehling I'll love to solve this. i'll soon share the link to test site.

**Comment by supunTE** [comment]
OK, I'm working

**Comment by supunTE** [comment]
Solved the issues.  https://stedirisuriya.github.io/stedirisuriya-fossasia.org/
Could you please check it now? @mariobehling

**Comment by supunTE** [comment]
image

**Review by mariobehling — CHANGES_REQUESTED** [review]
Breaks the existing smooth scrolling.

**Comment by supunTE** [comment]
Could you please explain me the situation?
There's no smooth scrolling existing?

**Pull request closed without merging**
