### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Propose Code of Conduct

### CODE REVIEW

**Comment by mariobehling** [comment]
COC is on https://coc.fossasia.org. It is sufficient. Please help with coding issues. Before we had people who add a COC in every single repo. This is not needed.

**Comment by BolajiAyodeji** [comment]
Alright!
Would check for Issues to be fixed

**Comment by BolajiAyodeji** [comment]
@mariobehling The Team page, how do Developers get there?
Do Fossasia have staffs or are they contributors?

**Comment by mariobehling** [comment]
People need to be long term contributors to be listed on the team page.

**Comment by BolajiAyodeji** [comment]
Alright!
Is there a basis for this or Duration of contribution?

**Pull request closed without merging**
