### PR TITLE
Improved '..More Events' and '..More Projects' List Item on header

### LINKED ISSUE #547: "MORE EVENTS"  in Events (nav-bar) needs some change
Screenshot from 2019-10-22 10-35-06

### PR DESCRIPTION
**Pull request by SauravP97**
The PR includes :
   1) Improved "..MORE EVENTS" list item in EVENTS (nav-bar)
   2) Improved "..MORE PROJECTS" list item in PROJECTS (nav-bar)
Fixed #547 

Screenshot (692)

### CODE REVIEW

**Review by aditya20t — APPROVED** [review]

**Review by liveHarshit — COMMENTED** [review]
Please provide a preview URL.

**Comment by SauravP97** [comment]
How will I do that ? I have the branch saved in my system locally

**Comment by liveHarshit** [comment]
> How will I do that ? I have the branch saved in my system locally

Use gh-pages for branch https://github.com/SauravP97/fossasia.org/tree/Improved-More_Events-List-Items

**Comment by SauravP97** [comment]
@liveHarshit Thanks for the guidance
         https://sauravp97.github.io/fossasia.org/

**Comment by liveHarshit** [comment]
IMO it was better earlier. Why it needs changes?

**Comment by liveHarshit** [comment]
@mariobehling This PR can be closed.

**Pull request closed without merging**
