### PR TITLE
Added Gitlab and Docker social profiles.

### PR DESCRIPTION
**Pull request by pranavkarthik10**
This is for GCI task https://codein.withgoogle.com/tasks/5343137837350912/?sp-organization=5183942706069504&sp-is_beginner=False. Updated Font Awesome library to house the new icons for Docker and Gitlab and updated old icons as well. Screenshot below displays the newly added social icons.
Fossasia updated social profiles

### CODE REVIEW

**Comment by mariobehling** [comment]
Hi, where does this "all.css" come from? Instead of changing this many files, lines of code and css would it be possible to include those two icons in the existing CSS?

**Comment by pranavkarthik10** [comment]
I agree that the code is quite excessive but the current version of Font Awesome to generate the icons is outdated and would be much better for any icon usage if updated.

**Comment by mariobehling** [comment]
We have a number of repositories and this change would require to change all the pages and a number of repositories. Would be better to find a way. This change would require a lot of work. What are the alternatives?

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Comment by pranavkarthik10** [comment]
Sorry about that, was stuck working on some other stuff. Created a new PR available here https://github.com/fossasia/fossasia.org/pull/591.

**Pull request closed without merging**
