### PR TITLE
Added team section for the page

### PR DESCRIPTION
**Pull request by Dishebh**
Added the team section in webpage as a fix for issue #564 

- [x] Feature Request

### Screenshot of the after result:
Screenshot from 2019-12-19 02-24-31

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please only do changes related to team members. I see unrelated changes and possibly automatic clean ups?

**Comment by Dishebh** [comment]
Sure, will do it in the next couple of hours

**Comment by Dishebh** [comment]
I'll close the PR and open a fresh one.

**Comment by liveHarshit** [comment]
Do changes in the same PR. Don't send multiple PR for the same issue. Follow: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by Dishebh** [comment]
@liveharshit thanks for referring. But, while working for another issue, I accidentally deleted the branch where I had committed the earlier changes. Sorry for any inconvenience, I will keep that in mind next time.

**Pull request closed without merging**
