### PR TITLE
Fixes: #158 Responsiveness issue

### PR DESCRIPTION
**Pull request by mani87**
Fixes: #158

### CODE REVIEW

**Comment by mani87** [comment]
@mariobehling can you please take a look at this sir?
Thanks :)

**Review by isuruAb — COMMENTED** [review]
@mani87  please mention the issue number you are referring, thank you 👍

**Comment by mani87** [comment]
@isuruAb https://github.com/fossasia/fossasia.org/issues/158 :)

**Review by isuruAb — COMMENTED** [review]
@mani87  please provide a preview link with your PR. please read this blog post for learn about best practices.
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

thank you 👍

**Comment by mani87** [comment]
@isuruAb can you please help me in that? Because i modified code so that alignment do not get disturb for different screens (screen with small sizes mainly) and i cannot see the preview untill its been added to the main code. (Can you tell me the way i can see my changes preview on different screen size).
Thankyou :)

**Comment by isuruAb** [comment]
@mani87  use inspect function of google chrome. there is a button for toggle device . use that.
screen shot 2017-09-30 at 11 41 17 am

**Comment by mani87** [comment]
Thankyou.. @isuruAb i am working on it...i'll commit again when done! :)

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
