### PR TITLE
upadte  theme-haemo.css

### PR DESCRIPTION
**Pull request by kavindyasinthasilva**
change some syntax and add some syntax

### CODE REVIEW

**Review by liveHarshit — COMMENTED** [review]
Provide preview url with gh pages.

**Comment by kavindyasinthasilva** [comment]
https://kavindyasinthasilva.github.io/hello-world/

**Comment by liveHarshit** [comment]
> https://kavindyasinthasilva.github.io/hello-world/

What is it?

**Comment by mariobehling** [comment]
Dont understand what this is for. Closing it therefore.

**Pull request closed without merging**
