### PR TITLE
i have solved extra space issue 

### PR DESCRIPTION
**Pull request by ghost**
screen shot 2018-01-14 at 3 30 22 pm

  screenshot after fixing the issue.

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Please provide a preview link :)

**Comment by ghost** [comment]
what is that?  I don't know git much, it would be great if u help me a bit.

**Comment by rupav** [comment]
@samarth-khajuria someone else is already working on it https://github.com/fossasia/fossasia.org/pull/275 before you. Preview link is the one from which we can see your changes on the website (and you don't need to post a screen shot then). Link is present in your settings tab of your forked repository.

**Comment by rupav** [comment]
In this case https://samarth-khajuria.github.io/fossasia.org/ .

**Review by rupav — APPROVED** [review]
Good work, but someone already took this issue before you. Please see if there is already a PR for a issue before working on to save time.

**Comment by ghost** [comment]
ok, and I really appreciate your suggestions.

**Comment by rupav** [comment]
This can be closed as resolved in https://github.com/fossasia/fossasia.org/pull/275.

**Pull request closed without merging**
