### PR TITLE
Solved issue #193

### PR DESCRIPTION
**Pull request by anshulwadhawan**
Fixes: #193 
I have changed the code by introducing a media query for devices having smaller screens.The text no longer overflows out of the box.
Please review the same.
@isuruAb 
Thanks :)

### CODE REVIEW

**Comment by dilpreetsio** [comment]
@anshulwadhawan Thanks for the PR. Can you please attach the screenshots & give a local deployment(gh-pages) for review? Cheers.

**Comment by anshulwadhawan** [comment]
Actually,the gh-pages fork in my personal repo is busy in some other PR.That's why i have made another branch.
The screenshot is attached :
issue

**Comment by anshulwadhawan** [comment]
@geekyd 
Sure.
You can review the page on - http://fossasia-issue193sol.bitballoon.com/
The screenshot is attached.
issue

**Review by dilpreetsio — CHANGES_REQUESTED** [review]
@anshulwadhawan The problem still persists on mobile screen devices with 320 X 480.
screen shot 2017-10-04 at 8 12 24 pm

**Review by isuruAb — COMMENTED** [review]
screen shot 2017-10-05 at 7 55 36 am

**Comment by anshulwadhawan** [comment]
@geekyd 
@isuruAb 
Please tell me what is the minimum width to be handled ?

**Comment by anshulwadhawan** [comment]
@geekyd 
@isuruAb 
I have made the required changes.Now,most common resolutions are handled.Please review them at -
http://fossasia-issue193sol.bitballoon.com/

Thanks :)

**Review by isuruAb — COMMENTED** [review]
screen shot 2017-10-07 at 8 58 27 pm
Please check this issue also

**Comment by anshulwadhawan** [comment]
Hello @isuruAb 
I have handled this issue too for most common screen resolutions.
Please tell me at what resolution are you facing this problem ?

**Review by isuruAb — COMMENTED** [review]
screen shot 2017-10-08 at 9 03 09 pm
Please check the site in this resolution

**Comment by mariobehling** [comment]
Thanks. Merging this as work in progress.

**Pull request merged**
