### PR TITLE
Update About FOSSASIA Footer text in all web pages #453 

### PR DESCRIPTION
**Pull request by khan0604**
Updated footer content and added hyperlinks in all web pages according to the issue #453

### CODE REVIEW

**Comment by khan0604** [comment]
@mariobehling Please review my changes
Preview Link : https://fossasia0604.000webhostapp.com/

**Comment by plxity** [comment]
@khan0604  Provide a preview link.

**Comment by khan0604** [comment]
@plxity Here is the Preview Link https://fossasia0604.000webhostapp.com/

**Comment by plxity** [comment]
LGTM 👍

**Comment by khan0604** [comment]
Thank You @plxity

**Review by plxity — APPROVED** [review]

**Comment by khan0604** [comment]
@mariobehling Please review my changes.

**Review by abishekvashok — APPROVED** [review]

**Comment by khan0604** [comment]
Thanks @mariobehling

**Pull request merged**
