### PR TITLE
Fixes #148 to make images of same width and height

### LINKED ISSUE #148: width of team member images are differ
width of team member images are differ in small screen sizes.
screen shot 2017-09-04 at 7 56 48 am
screen shot 2017-09-04 at 7 57 20 am

### PR DESCRIPTION
**Pull request by sounak98**
Fixes #148 Team member images are made to be of same width and height in smaller screen widths.

### CODE REVIEW

**Comment by mariobehling** [comment]
This does not seem to fix the issue #148. Please provide a test page on your own Github account and mention the issues you are solving in the PR. Cheers.

**Comment by isuruAb** [comment]
@sounak98  if you can provide few screenshots with your PR it is really easy for reviewers. please add few screenshots of your solution. cheers 👍

**Comment by sounak98** [comment]
Screenshots
---
screen shot 2017-09-08 at 2 27 10 pm
screen shot 2017-09-08 at 2 27 14 pm
screen shot 2017-09-08 at 2 27 17 pm

screen shot 2017-09-08 at 2 26 49 pm

**Comment by sounak98** [comment]
@isuruAb I have added the screenshots. Please review.

**Comment by mariobehling** [comment]
@isuruAb Made you a website admin. Would be great, if you could review those PRs.

**Comment by sounak98** [comment]
And this is the page where I will be adding every pull request details. https://sounak98.github.io/fossasia.html

**Pull request merged**
