### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by NoobSolver**
Added Some extra lines in readme.md file for organisation.

### CODE REVIEW

**Review by Chaitanyassr — COMMENTED** [review]
Why, I don't think there is need of that.

**Comment by NoobSolver** [comment]
It might be your wish

**Comment by NoobSolver** [comment]
It does not needed much but it creates a good impact I think.

**Comment by NoobSolver** [comment]
> Why, I don't think there is need of that.

@Chaitanyassr Have you thought my pr is correct or not.Please reply??

**Comment by Chaitanyassr** [comment]
> > Why, I don't think there is need of that.
> 
> @Chaitanyassr Have you thought my pr is correct or not.Please reply??

I believe the documetns

> > Why, I don't think there is need of that.
> 
> @Chaitanyassr Have you thought my pr is correct or not.Please reply??

well, i don’t see these changes are required as the current information in readme.md is well sufficient and this is not an issue also. Please solve an issue that requires more concern. thank you.

**Comment by Chaitanyassr** [comment]
> > Why, I don't think there is need of that.
> 
> @Chaitanyassr Have you thought my pr is correct or not.Please reply??

well, i don’t see these changes are required as the current information in readme.md is well sufficient and this is not an issue also. Please solve an issue that requires more concern. thank you.

**Comment by NoobSolver** [comment]
ok thanks

**Pull request closed without merging**
