### PR TITLE
Added new team member

### PR DESCRIPTION
**Pull request by Dishebh**
Added member Amrtya Mondal to the team

### Screenshot of the result:
Screenshot from 2019-12-25 16-45-10

Fix for issue #605

### CODE REVIEW

**Comment by Dishebh** [comment]
Solves PR #604

**Comment by liveHarshit** [comment]
Do not open a new PR for the same issue. Do changes in the last PR itself. 
Thank you

**Comment by Dishebh** [comment]
@liveharshit the last PR wasn't opened by me, so I don't think I can make changes to that.

**Comment by liveHarshit** [comment]
Provide preview URL with GitHub pages

**Comment by Dishebh** [comment]
@liveHarshit here's the test link:
https://dishebh.github.io/fossasia.org/team/

**Review by liveHarshit — CHANGES_REQUESTED** [review]
Use square image. 1:1 ratio

**Comment by Dishebh** [comment]
@liveHarshit How about now?
Test link: https://dishebh.github.io/fossasia.org/team/

**Review by liveHarshit — APPROVED** [review]

**Comment by mohitm15** [comment]
@liveHarshit close the issue too

**Pull request merged**
