### PR TITLE
Added Labyrinth to the projects dropdown !!

### PR DESCRIPTION
**Pull request by yashk0thari**
Solves issue no. #245 !! :D

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/sourflour.fossasia.org/ --> Preview Link :D

**Review by isuruAb — COMMENTED** [review]
please provide a demo link

**Comment by isuruAb** [comment]
dropdown overflows. please check.
screen shot 2018-01-03 at 12 55 42 am

**Comment by yashk0thari** [comment]
Its not working :| ; could you please help me ?? :D

**Comment by yashk0thari** [comment]
How do i fix this ??

**Pull request closed without merging**
