### PR TITLE
Add Sanskar Jethi as team member Fixes #270

### LINKED ISSUE #270: Add Sami Sanskar Jethi as team member
Add Sanskar Jethi as FOSSASIA team member

### PR DESCRIPTION
**Pull request by kubami9**
### Add Sanskar Jethi as team member. Fixes #270
Sanskar Jethi is an active member of FOSSASIA organisation, he's also displayed [here](https://github.com/orgs/fossasia/teams/fossasia-gci/members?after=Y3Vyc29yOnYyOpHOAULYKQ%3D%3D)

**Preview link: https://kubami9.github.io/fossasia.org/team**

### CODE REVIEW

**Comment by anshumanv** [comment]
Good going, please provide a test link, and lookup the indentation too.

**Comment by kubami9** [comment]
@anshumanv Ops, pardon, here is the preview link: https://kubami9.github.io/fossasia.org/team 😄

**Comment by anshumanv** [comment]
Nice, just fix the indentation and this should be good.

**Review by anshumanv — APPROVED** [review]

**Review by isuruAb — APPROVED** [review]

**Review by isuruAb — COMMENTED** [review]
please squash your commits

**Comment by kubami9** [comment]
Done 😃

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
