### PR TITLE
fixes #53 : added overflow property to permanently manage list items

### LINKED ISSUE #53: Fix height of gray events dropdown menu
The events dropdown menu currently does not show all links. Please ensure the box is automatically expanded to show all links of the menu on all FOSSASIA pages and subdomains.

screenshot from 2016-09-14 17 38 49

### PR DESCRIPTION
**Pull request by Shivang-Bhandari**
Added an overflow property to remove hard-coded CSS and manage lists for future ease.

### CODE REVIEW

**Comment by Shivang-Bhandari** [comment]
@mariobehling Please take a look

**Comment by mariobehling** [comment]
@Shivang-Bhandari Please provide a link to a github test page on your repository. Thank you.

**Comment by Shivang-Bhandari** [comment]
@mariobehling 
Link : https://shivang-bhandari.github.io/fossasia.org/

**Comment by Shivang-Bhandari** [comment]
@mariobehling i hope the issue is resolved

**Comment by jigyasa-grover** [comment]
@Shivang-Bhandari  looks good, do the same for [http://events.fossasia.org](http://events.fossasia.org) as well...

**Pull request merged**
