### PR TITLE
Fixes 446: Email in About Fossasia section made responsive

### LINKED ISSUE #446: Email not responsive in "About Fossasia" section
screenshot 35

### PR DESCRIPTION
**Pull request by garvitkhandelwal**
**Fixes #446 **

**Changes made:**   Email in **About** Section made responsive

**Preview Link:**   https://garvitkhandelwal.github.io/fossasia.org-preview/

**Screenshots of the issue:**  
screenshot 56

### CODE REVIEW

**Review by Dharmesh-Poddar — COMMENTED** [review]
problem still persist between width of 768-873

**Comment by garvitkhandelwal** [comment]
Can you send me a screenshot of it please

**Comment by garvitkhandelwal** [comment]
screenshot 57
Works fine on my machine

**Comment by Dharmesh-Poddar** [comment]
screenshot from 2018-12-24 00-22-55

**Review by pranav1698 — CHANGES_REQUESTED** [review]
I don't about a specific width but the site certainly is not responsive for all devices

**Comment by garvitkhandelwal** [comment]
screenshot 58
@Dharmesh-Poddar  Bootstrap takes a second or so to load itself depending on performance. Refreshing the page might help because it is working for me for those dimensions as well.

**Review by kksinghal — COMMENTED** [review]
The problem still exists .

**Comment by garvitkhandelwal** [comment]
Can you tell me at what dimensions it is giving the problem. Because it is working fine when I check it.

**Comment by kksinghal** [comment]
It is same as fossasia.org . It has not changed at all . Before it converts to sm , 768-900px , it overflows x . there is not much space for email to come in one line , so it overflows . Neither , we can show it in two lines , so you have to think of another way .

screenshot 2018-12-24 at 5 04 42 pm

**Comment by mariobehling** [comment]
This PR is not improving the site. Closing it therefore.

**Pull request closed without merging**
