### PR TITLE
Removed the redundancy

### PR DESCRIPTION
**Pull request by Dishebh**
Fixed issue #643 

Removed the extra profile of `Abhinav Raj` and `Praveen Ojha`

### CODE REVIEW

**Review by Chaitanyassr — APPROVED** [review]
great.

**Review by Chaitanyassr — CHANGES_REQUESTED** [review]
Please provide a deployed link.

**Comment by Dishebh** [comment]
> Please provide a deployed link.

Test Url: https://dishebh.github.io/fossasia.org/team/

**Review by Chaitanyassr — APPROVED** [review]

**Comment by Dishebh** [comment]
@mohitm15 pls review and merge. Thanks!

**Comment by mohitm15** [comment]
> @mohitm15 pls review and merge. Thanks!

@Dishebh 
LGTM,
Ask @mariobehling for merge.

**Pull request closed without merging**
