### PR TITLE
Google+ link is missing 

### PR DESCRIPTION
**Pull request by manmeet0307**
#242 Google+ link is missing 
Before:
image
After:
image
Link:
https://manmeet0307.github.io/fossasia.org/

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Can you please add some padding between the rows.

**Review by anshumanv — COMMENTED** [review]
Please style properly so there is sufficient spacing between horizontal rows.

**Comment by manmeet0307** [comment]
OK I will make necessary changes.

**Review by realslimshanky — APPROVED** [review]
Apart from the changes mentioned above LTGM.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@manmeet0307  Please `center align` the icons in the footer.

**Review by realslimshanky — APPROVED** [review]

**Comment by realslimshanky** [comment]
@manmeet0307 please squash your commits.

**Comment by realslimshanky** [comment]
@manmeet0307 please squash your commits. Your last five commits can be squashed.

**Comment by abishekvashok** [comment]
Ping @mariobehling is this needed?

**Comment by mariobehling** [comment]
No really needed as it is there on the bottom. Cheers.

**Pull request closed without merging**
