### PR TITLE
Add new team member

### PR DESCRIPTION
**Pull request by hoangdatngo**
Add new team member Yash Ladha to the team.

The deployment link: https://hoangdatngo.github.io/fossasia.org/team/

### CODE REVIEW

**Comment by hoangdatngo** [comment]
@hpdang, @mariobehling, @prateekiiest, @pranavkarthik10. Can any mentor please review my PR?

**Comment by prashant5878-shukla** [comment]
Some the icons are not working such as wekepedia , GitHub , Weibo ,gitlab

**Review by liveHarshit — CHANGES_REQUESTED** [review]
Follow the sequence. Do not add new team members in the middle.

**Comment by Chaitanyassr** [comment]
> Some the icons are not working such as wekepedia , GitHub , Weibo ,gitlab

Yes, because of a different PR #621 .

**Review by mariobehling — APPROVED** [review]

**Comment by hoangdatngo** [comment]
@mariobehling thank you very much!

**Pull request merged**
