### PR TITLE
fix: overlay on hover

### LINKED ISSUE #527: Add info area with expanding image title overlay effect on top of Android app screenshots
Please implement a simple dark gray overlay on the bottom (a square covering the bottom of the image). Avoid Gradients. Compare the general effect here: https://www.w3schools.com/howto/howto_css_image_overlay_title.asp

Only add one effect that moves up from the bottom and include 
* Name of app
* One Scroll-over show: Short description of the app. **Please make the effect in the way that the bottom gray bar expands from bottom to 2/3 of the app image - like make it moving in from the bottom with the description, please.**

Below the app screenshot please add a badge for a) Playstore and b) Fdroid.

screenshot from 2019-01-02 15-05-23

This issue is free to take up for anyone.

### PR DESCRIPTION
**Pull request by maze-runnar**
fixes: #527 
https://drive.google.com/file/d/1l3yeH9FdxtXkyko5I10B3gRi23KoyC4O/view?usp=sharing

### CODE REVIEW

**Review by liveHarshit — COMMENTED** [review]
Provide a preview url with gh-pages.

**Comment by maze-runnar** [comment]
https://youtu.be/JSYP40jh8XM

**Review by mariobehling — CHANGES_REQUESTED** [review]
Provide a preview url with gh-pages.

**Comment by maze-runnar** [comment]
https://maze-runnar.github.io/

**Comment by mariobehling** [comment]
Provide a preview url of the actual page on gh-pages. What I can see already is that the text is not shown completely.

**Comment by maze-runnar** [comment]
@mariobehling here is the preview url - 
https://maze-runnar.github.io/maze-runner.github.io/

**Review by mariobehling — CHANGES_REQUESTED** [review]
There are a lot of changes in this PR that are not related to the issue. Please squash your commits and only make changes related to this issue.

**Comment by mohitm15** [comment]
@maze-runnar Status over this issue??

**Pull request closed without merging**
