### PR TITLE
Added a team member

### PR DESCRIPTION
**Pull request by saarthakchats**
Mohit Sharma's photo and credentials

### CODE REVIEW

**Comment by saarthakchats** [comment]
@ms10398

**Comment by the-codingninja** [comment]
Please provide a preview link

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/satsfossasia.org/team

**Comment by saarthakchats** [comment]
@ms10398

**Review by the-codingninja — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]

**Pull request merged**
