### PR TITLE
Add Weibo to Social Footer menu

### PR DESCRIPTION
**Pull request by kksinghal**
Added Weibo icon link to the social menu in footer . 
Preview Link https://ksninja.github.io/fossasia.org/
Issue no #387

### CODE REVIEW

**Comment by pythongiant** [comment]
LGTM

**Review by pranav1698 — APPROVED** [review]
LGTM! GCI mentors will be able to provide more hindsight for this pr

**Review by pythongiant — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please also include it in all other pages of the website about etc.

**Comment by kksinghal** [comment]
@mariobehling  I have a suggestion . As it seems in very page, the footer is same , we can make a separate footer.html and link it to all the required files . It will also prevent duplication of code .

**Comment by mariobehling** [comment]
Please keep it simple for now. Further changes should be done within a larger vision.

**Comment by kksinghal** [comment]
@mariobehling Changes pushed . Please review .
In the apply/index.html    , the github icon was missing . I added that too .

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
