### PR TITLE
Added a Summit's DropDown

### PR DESCRIPTION
**Pull request by yashk0thari**

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/forawhile.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
Please review and merge if no conflicts :D

**Comment by yashk0thari** [comment]
??

**Review by harshit98 — APPROVED** [review]

**Comment by mariobehling** [comment]
This should not have been done. We dont want to divert and we dont need a separate menu item at the moment.

**Pull request merged**
