### PR TITLE
(#398)(#432)Added names and details of apps on hover

### LINKED ISSUE #398: Add name of app below each screenshot of the Android apps
What style can we implement to show the name below the Android apps that looks good?

### LINKED ISSUE #432: No details or hover on Android Apps
These apps should have the name coming on hover
screenshot 2018-12-16 at 1 37 36 pm

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #398 
Fixes #432 
[Preview](https://saarthakchats.github.io/papishs/)

### CODE REVIEW

**Comment by saarthakchats** [comment]
Ping @mariobehling

**Review by pythongiant — CHANGES_REQUESTED** [review]
Seems unreadable. please darken the overlay

**Comment by saarthakchats** [comment]
Done

**Comment by kksinghal** [comment]
Your preview link is not working .

**Comment by saarthakchats** [comment]
Updated @KSNINJA @pythongiant

**Comment by Pipe-Runner** [comment]
@saarthakchats I would suggest even higher gradient. It is still not readable

**Comment by pythongiant** [comment]
Preview link not working

**Comment by saarthakchats** [comment]
Updated @pythongiant

**Comment by mariobehling** [comment]
Nice! Merging it. Could you make the gradient a bit darker as suggested by @AakashMallik in the next PR, please? Thank you!

**Comment by saarthakchats** [comment]
Ok sure @mariobehling 
Thanks for merging!

**Pull request merged**
