### PR TITLE
extra space removed from the team page 

### PR DESCRIPTION
**Pull request by Ridvmodi**
Deployment link: [fossasia.surge.sh](https://fossasia.surge.sh)

Before changes
screenshot 274
After changes extra space removed 
screenshot 275

### CODE REVIEW

**Review by NaviRocker — APPROVED** [review]

**Review by Akshat-Jain — COMMENTED** [review]
Please provide a deployment link or screenshots showing what is being changed in this PR. Thanks! :-)

**Comment by Ridvmodi** [comment]
@Akshat-Jain  check issue No #341 i already put the screenshots there brother

**Review by samagragupta — COMMENTED** [review]
Please provide the **deployment link** as said by @Akshat-Jain .

**Comment by Ridvmodi** [comment]
Check it out at fossasia.surge.sh @Akshat-Jain @samagragupta

**Review by samagragupta — COMMENTED** [review]
Please provide the changed screenshot in PR description or provide the deployment link in PR description.

**Comment by Ridvmodi** [comment]
check it out @samagragupta @Akshat-Jain

**Comment by Ridvmodi** [comment]
did you check it ?@Akshat-Jain @samagragupta

**Comment by Ridvmodi** [comment]
deployment link updated

**Review by Pipe-Runner — APPROVED** [review]

**Review by sarnava1 — APPROVED** [review]

**Review by isuruAb — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]

**Review by mkmar01 — APPROVED** [review]

**Review by sakshee-19 — APPROVED** [review]

**Review by simsausaurabh — APPROVED** [review]

**Review by nikit19 — APPROVED** [review]

**Pull request merged**
