### PR TITLE
Added back to the top button on scrolling down, issue-#474

### PR DESCRIPTION
**Pull request by Chaitanyassr**
back to the top button on scrolling down added at the bottom right side.
deployed link - https://chaitanyassr.github.io/fossasia.org/
@mariobehling Sir, please check.

### CODE REVIEW

**Comment by Chaitanyassr** [comment]
@mariobehling Sir, can you please check if this solve issue #474 ...thank you.

**Review by mohitm15 — APPROVED** [review]

**Review by mohitm15 — COMMENTED** [review]
@Chaitanyassr there's already a `back to top` menu option at bottom.

Screenshot 2020-01-19 02:17:11

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr there's already a `back to top` menu option at bottom.
> 
> Screenshot 2020-01-19 02:17:11
Thank you,
yes, but we can not use it when we are in the middle of the page. So i solved the issue #474 which says to include back to the top button on scrolling down(at the bottom right corner).

**Comment by Chaitanyassr** [comment]
@hpdang @prateekiiest @cweitat @mariobehling , it has been 7 days, can any mentor please review my PR.

**Comment by prateekiiest** [comment]
@Chaitanyassr you havent assigned me to review this PR. So I didnt get any notification.

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr you havent assigned me to review this PR. So I didnt get any notification.

i m sorry for that.
 Sir, please review.

**Review by prateekiiest — APPROVED** [review]
Looks good to me.

**Comment by Chaitanyassr** [comment]
> back to the top button on scrolling down added at the bottom right side.
> deployed link - https://chaitanyassr.github.io/fossasia.org/
> @mariobehling Sir, please check.

it has been days, can someone merge my PR.

**Pull request merged**
