### PR TITLE
Decreased padding in input

### LINKED ISSUE #260: Excessive padding hinders proper view of amount
Due to excessive padding proper view of amount is hindered in Donate with Credit Card in https://fossasia.org/donate.html

screenshot from 2018-01-10 04-52-30

I would like to work on this.

### PR DESCRIPTION
**Pull request by sayak119**
Fixes #260 

**Previously**
screenshot from 2018-01-10 04-52-30

**After change**
screenshot from 2018-01-10 05-00-24

**Demo link** - http://accurate-front.surge.sh/donate.html

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
The preview link isn't working properly. Please check console errors to fix the link.

**Comment by sayak119** [comment]
screencast_wednesday-10-january-2018_05_03_07-ist

@akshatnitd it's working

**Review by rupav — APPROVED** [review]
good work.

**Review by anshumanv — APPROVED** [review]
LGTM

**Pull request merged**
