### PR TITLE
Fixes issue #386

### PR DESCRIPTION
**Pull request by garvitkhandelwal**
Issue #386 
Made navbar completely responsible. Now it won't overlap with the logo or come to the next line.

### CODE REVIEW

**Comment by garvitkhandelwal** [comment]
screenshot 30
This is the preview of the browser after the changes.

**Review by pranav1698 — COMMENTED** [review]
A Preview Link will be really helpful for testing the changes

**Comment by garvitkhandelwal** [comment]
Sorry but I'm not able to create a preview link. Working on how to create one

**Comment by garvitkhandelwal** [comment]
Here is the preview link :- https://garvitkhandelwal.github.io/fossasia.org-preview/

**Comment by plxity** [comment]
@garvitkhandelwal Fossasia logo and NavBar elements are not in one line.
Have a look at https://2019.fossasia.org/ NavBar and make changes.

**Review by plxity — CHANGES_REQUESTED** [review]
@garvitkhandelwal Fossasia logo and NavBar elements are not in one line.
Have a look at https://2019.fossasia.org/ NavBar and make changes.

**Comment by mariobehling** [comment]
Closing it due to inactivity. Please follow up once you are ready. Thanks!

**Pull request closed without merging**
