### PR TITLE
 Issue #637 Section-header mid cut solved

### PR DESCRIPTION
**Pull request by ayushmankumar7**
Solved it. Hope you like it.

Initially

Screenshot from 2020-01-13 20-26-18

Final

Screenshot from 2020-01-13 20-23-42

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you give me a test link?

**Comment by ayushmankumar7** [comment]
https://ayushmankumar7.github.io/fossasia.org/ 
Here it is

**Comment by abishekvashok** [comment]
Breaks on mobile. Please recheck

**Comment by ayushmankumar7** [comment]
Check it now.

**Review by Raunaksingh100 — APPROVED** [review]
LGTM

**Comment by ayushmankumar7** [comment]
Thanks

**Pull request closed without merging**
