### PR TITLE
Updated donate.html and created .css/donate.css

### PR DESCRIPTION
**Pull request by rajakedia1**
Issue: Implement donation and supporter funding for fossasia.org #45

Here, 
Quick Donate and Regular Supporter Option has been added ( it can be checked by looking in donate.html).
Option related to above two has been added. 
Payment portal (Paypal and stripe) is still to be managed.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you.

Please provide a test page and screenshot.

Please use the existing css.

**Comment by rajakedia1** [comment]
Here, I am uploading Screenshot of the donate.html page. User can select option(  Quick Donate or Regular Donor). Depending on that, they can select the amount and proceed further.
donate_screenshot.
And Regarding css file, I am deleting that. I am send a new pull request in which there is only updated donate.html.

**Comment by rajakedia1** [comment]
You can close this pull request. Thank you.

**Comment by mariobehling** [comment]
Thank you! Issue has been resolved.

**Pull request closed without merging**
