### PR TITLE
rm duplicate page

### PR DESCRIPTION
**Pull request by KrishMunot**
Duplicate of https://github.com/fossasia/fossasia.org/tree/gh-pages/contact

### CODE REVIEW

**Comment by gureks** [comment]
Hi.
Sorry but this is not a duplicate.  Please go through both the pages once to check what it does.

**Comment by mariobehling** [comment]
There is no issue here.

**Comment by KrishMunot** [comment]
No issue with my commit?

**Comment by jigyasa-grover** [comment]
@KrishMunot The issue ain't valid, no duplicity exists.

**Comment by KrishMunot** [comment]
@mariobehling @jig08 The "contacts" page was empty and had nothing in there that was significant. 
If there is something is very interesting about it or a purpose, do enlighten me.

**Pull request closed without merging**
