### PR TITLE
Fixed the section header

### PR DESCRIPTION
**Pull request by Dishebh**
Fixed the section for mobile resolutions.

Fix for issue #596 

### Screenshot of the result:
Screenshot from 2019-12-21 21-58-11

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a test link. I see "FOSSASIA" is in blue suddenly. Not sure, why.

**Comment by Dishebh** [comment]
@mariobehling here's the preview link: 
https://dishebh.github.io/fossasia.org/

**Review by mariobehling — CHANGES_REQUESTED** [review]
Does not solve the problem. Heading disappears. Section bottom is cut off.

Screenshot from 2019-12-23 00-19-06

**Comment by Dishebh** [comment]
Preview Link:
https://dishebh.github.io/fossasia.org/

what about now?

**Comment by Dishebh** [comment]
@mariobehling pls have a look at the PR, see if it solves the issue?

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
