### PR TITLE
added project ideas link in the html file

### PR DESCRIPTION
**Pull request by Jaggu-123**
I have added the link of Project Ideas.
Issue: #481 
Preview: https://jaggu-123.github.io/fossasia.org/
screenshot 156

### CODE REVIEW

**Comment by mariobehling** [comment]
You need to expand the height of the menu dropdown as well.

**Comment by Jaggu-123** [comment]
@mariobehling 
screenshot 157

**Comment by mariobehling** [comment]
Thank you. Please add it in all pages in this repo.

**Comment by Jaggu-123** [comment]
@mariobehling It has been added in all the pages in the repo. The one's left are the pages whose HTML page is not in this repo. If there is any way to add in those pages also then please suggest me.

**Pull request merged**
