### PR TITLE
Flickr

### PR DESCRIPTION
**Pull request by Jaggu-123**
Issue: #460 
Preview: https://jaggu-123.github.io/fossasia.org/

### CODE REVIEW

**Comment by kksinghal** [comment]
Please provide a brief description of what you solved . 
Squash your commits.
Else LGTM .
Also , please remove my mention from the description . I am not a mentor . Comment on Gitter for mentors to review .

**Comment by Jaggu-123** [comment]
There was an extra margin-bottom which was coming on hovering the dropdown li .
I just removed it, then it works good.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Take out the unnecessary changes in the css please

**Comment by mariobehling** [comment]
Includes a number of unnecessary changes. Closing it due to inactivity.

**Pull request closed without merging**
