### PR TITLE
Adding team member "Sean McGregor"

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Test Link
https://yashkumarverma.github.io/fossasia.org/team

Added mentor:
Sean McGregor

### CODE REVIEW

**Comment by mariobehling** [comment]
He is an associated member, not a FOSSASIA member himself.

**Comment by YashKumarVerma** [comment]
@mariobehling I found him in the team so added. Who can I add ?

**Comment by mariobehling** [comment]
Looks like our team members are complete. If you could get better images for some people, e.g. Nicco Kunzmann that would be something that would be great.

**Comment by YashKumarVerma** [comment]
sure @mariobehling

**Comment by rupav** [comment]
@mariobehling @YashKumarVerma then I am not modifying that GCI task. Only 3 days left anyways. Good luck.

**Pull request closed without merging**
