### PR TITLE
Fix issue #474

### PR DESCRIPTION
**Pull request by pkspyder007**
@mariobehling  I have added a scroll to top button functionality. The live version can be seen at https://fossasia.netlify.com
Please refer line 297 for my code. This happened due to Prettier. Sorry for the inconvenience.

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
The issue is that there is already a smooth scrolling feature and your changes break this existing feature partly. I have to click twice on top menu links that link into the website to get things moving for example. Please try to use the existing scrolling function of the site.

**Comment by pkspyder007** [comment]
@mariobehling I studied the existing function and modified my solution now it uses the existing one.
please review it.

**Comment by pkspyder007** [comment]
@mariobehling  please review this pull request and give your comments on it.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Clicking on existing links still results in a delay with the changed implementation, e.g. try on the footer "Back to top link".

**Comment by Chaitanyassr** [comment]
@mariobehling Sir,
it looks like this pr is inactive, can I submit my own.

**Pull request closed without merging**
