### PR TITLE
solved issue  #202 problem in dropdown menu when we reduce the screen width less then 769px(approx)

### LINKED ISSUE #202: problem in dropdown menu when we reduce the screen width less then 769px(approx)
dropdowns 
1.PROJECTS
2.EVENTS
not completely visible when we reduce screen width less the 769(approx)
fossasia 1
fossasia 3
fossasia 2
fossasia 4

can I work on this issue?

### PR DESCRIPTION
**Pull request by luckykumardev**
fixed: #202 
@isuruAb 
I have deleted the inline styling of class 'nav-dropdown' index.html and give 'projects' and 'events' classes to dropdown projects and events. and then in theme-lava.css I give min-height property to classes 'projects', 'events' and 'nav-dropdown'

fossasia 2 1
fossasia 4 1

thanks :)

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
@luckykumardev  please resolve conflicts

**Comment by luckykumardev** [comment]
@isuruAb  conflicts have resolved.

**Comment by isuruAb** [comment]
@luckykumardev  please squash all commits also please provide a preview link

**Comment by mariobehling** [comment]
Ok, merging this.

**Pull request merged**
