### PR TITLE
Change Activated Links from Blue to Light Gray

### LINKED ISSUE #372: Activated link blue - expected: It should by light gray
Activated link blue - expected: It should by light gray

screenshot from 2018-11-23 14-06-40

### PR DESCRIPTION
**Pull request by rcya1**
Fixes #372 

**Changes:**
- Turns the active color of the links from blue to light gray on the Flickr link and on the Links in "Interested in coding for FOSSASIA? Register on our application page for internship and job openings, subscribe to our newsletter for announcements and start engaging by doing a mini-project."

[Preview Link](https://ryan10145.github.io/fossasia.org/)

**Screenshots:**

image
image

### CODE REVIEW

**Review by sarnava1 — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]
LGTM :+1:

**Review by mkmar01 — APPROVED** [review]

**Review by championpaddler — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please change the existing CSS instead of introducing a new style.

**Comment by rcya1** [comment]
@mariobehling Which existing css are you talking about? `text-white` is an already existing css style defined in the themes, but I put in a bit of styling to make sure that it doesn't show up as blue when active.

**Review by samagragupta — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Comment by rcya1** [comment]
@samagragupta Done

**Comment by abishekvashok** [comment]
The bug to be sold is this: why only a single link turns blue and doesn't behave like other links. Instead of adding new and new styles, can you come up with the exact cause, and rectify it?

**Comment by rcya1** [comment]
@abishekvashok Ok, thanks for the clarification. I'll work on that now.

**Comment by rcya1** [comment]
@abishekvashok @mariobehling From what I can see, the reason the links are turning blue is that in bootstrap, a:focus is defined to have a color of #2a6496, which is making the links turn blue. Should I add a css style that changes the a:focus instead of text-white:focus to light gray? I don't see a way I can avoid adding new styles since the issue comes from how bootstrap is set up and we want to change that part of bootstrap to use our color.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
